# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HS_ResourceLink_model',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plugins_hs_resourcelink_model', serialize=False, to='cms.CMSPlugin')),
                ('display_text', models.CharField(blank=True, default='', help_text="Display Text for resource link (defaults to 'Resource Link url')", max_length=255, verbose_name='Resource Display Text')),
                ('resource_type', models.CharField(default='', help_text='Please supply a HydroShare Resource type', max_length=64, verbose_name='HydroShare Resource Type')),
                ('resource_link', models.URLField(default='', help_text='Please supply a HydroShare Resource Link', verbose_name='HydroShare Resource Link')),
            ],
            options={
                'verbose_name': 'HydroShare Resource Link',
                'verbose_name_plural': 'HydroShare Resource Links',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
