# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', help_text='Please enter a name for this Lesson', max_length=250, verbose_name='Lesson Name'),
        ),
    ]
