# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-27 13:40
from __future__ import unicode_literals

from cms.api import add_plugin
from cms.utils.copy_plugins import copy_plugins_to
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


# NOTE: Modules should be cleared out before performing this migration

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [


        # modify unique together constraints for affected models to remove dependencies
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([]),
        ),

        # modify lesson model
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('position',), 'verbose_name_plural': 'Lessons'},
        ),

        migrations.AddField(
            model_name='lesson',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='parent_lesson',
            field=models.ForeignKey(blank=True, default=None, help_text='Specify a Parent Lesson for this Sub-Lesson.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_lessons', to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pub_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='publish_status',
            field=models.CharField(choices=[('draft_only', 'Draft Only'), ('draft_published', 'Published Draft'), ('current_publication', 'Current Publication'), ('past_publication', 'Previously Published Copy')], default='draft_only', editable=False, max_length=25),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_copy',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copy', to='core.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),

        migrations.AddField(
            model_name='lesson',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='depth_label',
            field=models.CharField(default='Module', help_text='The depth-level label for this lesson', max_length=10,
                                   verbose_name='Depth Label'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False,
                                                            help_text='Please enter a unique slug for this Lesson (can autogenerate from name field)',
                                                            max_length=8, populate_from=('ref_id',), unique=True,
                                                            verbose_name='slug'),
        ),

        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set([('parent_lesson', 'name')]),
        ),

        # modify sections
        migrations.AlterField(
            model_name='section',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False,
                                                            help_text='Please enter a unique slug for this Section (can autogenerate from name field)',
                                                            max_length=8, populate_from=('ref_id',), unique=True,
                                                            verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),

        #############################################
        # perform data migration
        #############################################
        #migrations.RunPython(clear_modules),

        # finish modifying lessons
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),


        # remove linked module fields
        migrations.RemoveField(
            model_name='module',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='module',
            name='published_copy',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tags',
        ),

        # remove linked topic fields
        migrations.RemoveField(
            model_name='topic',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='module',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),

        # Delete Depreciated models Module/Topic
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
