# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_restructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('definition', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=64)),
                ('task', models.CharField(max_length=64)),
                ('degree', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=64)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Learning_Level')),
            ],
        ),
        migrations.AddField(
            model_name='learning_objective',
            name='outcomes',
            field=models.ManyToManyField(to='core.Learning_Outcome'),
        ),
        migrations.AddField(
            model_name='learning_objective',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Learning_Verb'),
        ),
    ]
