# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 17:18
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180417_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='ref_id',
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, help_text='Please enter a unique slug for this Topic (can autogenerate from name field)', max_length=64, populate_from=('name',), unique=True, verbose_name='slug'),
        ),
    ]
