# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20181108_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(
                    default=True,
                    help_text='Allow this person edit the Lesson? if not checked, user will only be given view permissions to the Draft.'
                )),
                ('collaboration_date', models.DateField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(
                    help_text='User being given Draft-View Permissions.',
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lesson')),
            ],
        ),

        migrations.AlterModelOptions(
            name='collaboration',
            options={'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),


        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together=set([('publication', 'collaborator')]),
        ),

        migrations.AddField(
            model_name='lesson',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborations', through='core.Collaboration', to=settings.AUTH_USER_MODEL),
        ),
    ]
