# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_collaboration_table_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='derived_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='derived_lesson_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspired_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='derived_lesson_slug',
            field=models.CharField(default=None, editable=False, max_length=8, null=True),
        ),
    ]
