# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cloned_lesson_derived_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(blank=True, default='', help_text="Display Text for resource link (defaults to 'Resource Link url')", max_length=255, verbose_name='Resource Display Text')),
                ('resource_type', models.CharField(default='', help_text='Please supply a HydroShare Resource type', max_length=64, verbose_name='HydroShare Resource Type')),
                ('resource_link', models.URLField(default='', help_text='Please supply a HydroShare Resource Link', verbose_name='HydroShare Resource Link')),
                ('activity', models.ForeignKey(default=None, help_text='Please specify the Activity Section for this Resource.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.ActivitySection')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
