# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activity_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoice_answer',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiselect_answer',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='multichoice_answer',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='multiselect_answer',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
