# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activity_resources'),
    ]

    operations = [

        migrations.AlterField(
            model_name='quizquestion',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False,
                                   verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(
                choices=[('multi-choice', 'Multiple Choice'), ('multi-select', 'Multiple Selection')],
                default='multi-choice', max_length=25),
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('answer_text', models.TextField(default='')),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Quiz-Answer',
                'verbose_name_plural': 'Quiz-Answers',
            },
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ('position',), 'verbose_name': 'Quiz-Question',
                     'verbose_name_plural': 'Quiz-Questions'},
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='changed_date',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(default=None, help_text='Please specify a Quiz Section to map this question to.',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='questions',
                                    to='core.QuizSection'),
        ),
        migrations.DeleteModel(
            name='MultiChoice_answer',
        ),
        migrations.DeleteModel(
            name='MultiChoice_question',
        ),
        migrations.DeleteModel(
            name='MultiSelect_answer',
        ),
        migrations.DeleteModel(
            name='MultiSelect_question',
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(default=None, help_text='Please specify a Quiz Question to map this answer to.',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                    to='core.QuizQuestion'),
        ),

    ]
