# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_learning_outcome_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_objective',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Lesson'),
            preserve_default=False,
        ),
    ]
