# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_Alter_quiz_question_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(blank=False, default='', help_text='Display Text for Application in your module (Tab Text)', max_length=255, verbose_name='App Name')),
                ('app_link', models.URLField(default='', help_text='Please supply a URL to a valid HydroShare Hosted Application', verbose_name='Application URL')),
                ('lesson', models.ForeignKey(default=None, help_text='Please specify the parent Lesson for this Application.', on_delete=django.db.models.deletion.CASCADE, related_name='app_refs', to='core.Lesson')),
            ],
            options={
                'verbose_name': 'Application Reference',
                'verbose_name_plural': 'Application Reference',
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_link',
            field=models.URLField(default='', help_text='Please supply a Resource URL', verbose_name='Resource Link'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(default='', help_text='Please supply a HydroShare Resource type', max_length=64, verbose_name='Resource Type'),
        ),

        # remove unique name constraint amongst lessons/sections
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([]),
        ),
    ]
