# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_learning_objective_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_verb',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
