# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_Lesson_HS_App_References'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_objective',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Lesson'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='learning_verb',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
