# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_learning_obj_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_objective',
            name='lesson',
            field=models.ForeignKey(help_text='Specify a lesson for this Learning Objective.', on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='core.Lesson'),
        ),
        migrations.AlterField(
            model_name='learning_objective',
            name='outcomes',
            field=models.ManyToManyField(blank=True, to='core.Learning_Outcome'),
        ),
        migrations.AlterField(
            model_name='learning_objective',
            name='verb',
            field=models.ForeignKey(help_text='Specify a verb for this Learning Objective', on_delete=django.db.models.deletion.CASCADE, to='core.Learning_Verb'),
        ),
        migrations.AlterField(
            model_name='learning_verb',
            name='level',
            field=models.ForeignKey(help_text='Specify the learning level for this verb.', on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='core.Learning_Level'),
        ),
    ]
