# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.apps.uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_temp', models.BooleanField(default=True, help_text='Checking this option marks the image for deletion within 24 hours. (allowing temp image hosting for use in the editor)', verbose_name='Temp Image')),
                ('img', models.ImageField(upload_to=src.apps.uploads.models.path_and_rename)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'ordering': ('creation_date',),
            },
        ),
    ]
